Fix osmnx dependency to version 1
Without this it will try to install osmnx version 2, which had breaking
changes and causes prettymaps to fail with the error
```
AttributeError: module 'osmnx' has no attribute 'project_gdf'. Did you mean: 'project_graph'?
```